import "./styles.kidstvb2b.css";

export const metadata = {
  title: "KidsTV",
  description: "Generated by create next app",
};

export default function kidsTvLayout({ children }) {
  return <>{children}</>;
}
